title: Knife Talk
description: The podcast for knife nerds hosted by Craig, Geoof & Mareko

url: 
baseurl: "/"
paginate_path: "episode/page:num/"
permalink: :slug

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Hosts
   url: /hosts
 - title: Sponsorship
   url: /sponsorship
 - title: Suppliers
   url: /suppliers
 



google_analytics: "UA-97989743-2"



# Note that when viewing locally (bundle exec jekyll serve) the baseurl should be "". To build for GitHub pages it should be "/".